let seuVotoPara = document.querySelector('.divisao-1-1 span')
let cargo = document.querySelector('.divisao-1-2 span')
let descricao = document.querySelector('.divisao-1-4 span')
let aviso = document.querySelector('.divisao-1-2')
let lateral = document.querySelector('.divisao-1-right')
let numeros = document.querySelector('.divisao-1-3')